[2018-02-15 14:29:18,727] [ERROR] [Client]: java.net.ConnectException: Connection refused: connect
[2018-02-15 14:29:18,873] [ERROR] [ServerWorker]: java.lang.NullPointerException
[2018-02-15 14:31:07,656] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: src\dataBase.properties (Не удается найти указанный файл)
[2018-02-15 14:32:50,482] [ERROR] [ServerWorker]: java.net.SocketException: Socket is closed
[2018-02-15 14:35:58,828] [ERROR] [ServerWorker]: java.net.SocketException: Socket is closed
[2018-02-15 14:36:49,983] [ERROR] [ServerWorker]: java.net.SocketException: Socket is closed
[2018-02-15 14:40:41,330] [ERROR] [ServerWorker]: java.net.SocketException: Socket is closed
[2018-02-15 15:02:10,680] [ERROR] [ServerWorker]: java.net.SocketException: Socket is closed
[2018-02-15 15:02:23,742] [ERROR] [ServerWorker]: java.net.SocketException: Socket is closed
[2018-02-15 15:03:56,181] [ERROR] [ServerWorker]: java.net.SocketException: Socket is closed
[2018-02-15 15:33:54,655] [ERROR] [NewClient]: Connection problems!
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at com.senla.bookshop.newClient.NewClient.main(NewClient.java:20)
[2018-02-15 15:34:29,415] [ERROR] [NewClient]: Connection problems!
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at com.senla.bookshop.newClient.NewClient.main(NewClient.java:20)
[2018-02-15 15:35:03,915] [ERROR] [NewClient]: Connection problems!
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at com.senla.bookshop.newClient.NewClient.main(NewClient.java:20)
[2018-02-15 15:35:05,793] [ERROR] [NewClient]: Connection problems!
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at com.senla.bookshop.newClient.NewClient.main(NewClient.java:20)
[2018-02-15 15:35:10,708] [ERROR] [NewClient]: Connection problems!
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at com.senla.bookshop.newClient.NewClient.main(NewClient.java:20)
[2018-02-15 16:36:10,980] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: src\dataBase.properties (Не удается найти указанный файл)
[2018-02-15 16:36:30,011] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: src\dataBase.properties (Не удается найти указанный файл)
[2018-02-15 16:38:24,476] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: src\dataBase.properties (Не удается найти указанный файл)
[2018-02-15 16:42:46,851] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: src\dataBase.properties (Не удается найти указанный файл)
[2018-02-15 16:43:46,691] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: src\dataBase.properties (Не удается найти указанный файл)
[2018-02-15 16:50:26,939] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: src\dataBase.properties (Не удается найти указанный файл)
[2018-02-15 16:52:36,427] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: src\dataBase.properties (Не удается найти указанный файл)
[2018-02-15 16:53:41,619] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: src\dataBase.properties (Не удается найти указанный файл)
[2018-02-15 17:01:50,027] [ERROR] [NewClient]: Connection problems!
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at com.senla.bookshop.client.NewClient.main(NewClient.java:20)
[2018-02-15 17:03:01,404] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: src\dataBase.properties (Не удается найти указанный файл)
[2018-02-15 17:05:18,837] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: dataBase.properties (Не удается найти указанный файл)
[2018-02-15 17:08:41,459] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: dataBase.properties (Не удается найти указанный файл)
[2018-02-15 17:13:08,652] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: dataBase.properties (Не удается найти указанный файл)
[2018-02-15 17:14:17,956] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: dataBase.properties (Не удается найти указанный файл)
[2018-02-15 17:21:47,152] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: dataBase.properties (Не удается найти указанный файл)
[2018-02-15 17:25:30,487] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: dataBase.properties (Не удается найти указанный файл)
[2018-02-15 17:26:32,762] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: dataBase.properties (Не удается найти указанный файл)
[2018-02-15 17:29:16,860] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: dataBase.properties (Не удается найти указанный файл)
[2018-02-15 17:30:23,813] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: dataBase.properties (Не удается найти указанный файл)
[2018-02-15 17:32:52,437] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: dataBase.properties (Не удается найти указанный файл)
[2018-02-15 17:34:18,573] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: dataBase.properties (Не удается найти указанный файл)
[2018-02-15 17:36:44,565] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: BookShop\dataBase.properties (Системе не удается найти указанный путь)
[2018-02-15 17:42:34,677] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: src\dataBase.properties (Не удается найти указанный файл)
[2018-02-15 17:43:47,693] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: src\dataBase.properties (Не удается найти указанный файл)
[2018-02-15 17:44:30,301] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: dataBase.properties (Не удается найти указанный файл)
[2018-02-15 22:24:47,546] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: src\dataBase.properties (Не удается найти указанный файл)
[2018-02-15 22:26:09,874] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: src\dataBase.properties (Не удается найти указанный файл)
[2018-02-15 22:26:39,738] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: src\dataBase.properties (Не удается найти указанный файл)
[2018-02-15 22:27:50,954] [ERROR] [PropertyHolder]: java.io.FileNotFoundException: src\dataBase.properties (Не удается найти указанный файл)
[2018-02-15 22:37:55,635] [ERROR] [Loader]: java.io.FileNotFoundException: src\dataBase.properties (Не удается найти указанный файл)
